Add test for non-standard sample rates.
Signed-off-by: Stefan Westerfeld <stefan@space.twc.de>

diff --git a/tests/test-common.sh.in b/tests/test-common.sh.in
--- a/tests/test-common.sh.in
+++ b/tests/test-common.sh.in
@@ -11,6 +11,12 @@ die()
   exit 1
 }
 
+audiowmark()
+{
+  echo >&2 ==== audiowmark "$@" ====
+  $AUDIOWMARK --strict "$@" || die "failed to run audiowmark $@"
+}
+
 audiowmark_add()
 {
   if [ "x$Q" == "x1" ]; then
