Add hls test (needs to be run manually for now).
Signed-off-by: Stefan Westerfeld <stefan@space.twc.de>

diff --git a/tests/test-common.sh.in b/tests/test-common.sh.in
--- a/tests/test-common.sh.in
+++ b/tests/test-common.sh.in
@@ -18,7 +18,7 @@ audiowmark()
   else
     echo >&2 ==== audiowmark "$@" ====
   fi
-  $AUDIOWMARK --strict "$@" || die "failed to run audiowmark $@"
+  $AUDIOWMARK $AUDIOWMARK_Q --strict "$@" || die "failed to run audiowmark $@"
 }
 
 audiowmark_add()
