TESTS: check snr in wav pipe test to catch conversion errors
Signed-off-by: Stefan Westerfeld <stefan@space.twc.de>

diff --git a/tests/test-common.sh.in b/tests/test-common.sh.in
--- a/tests/test-common.sh.in
+++ b/tests/test-common.sh.in
@@ -44,9 +44,18 @@ audiowmark_cmp()
 
 check_length()
 {
-  local in1=$(audiowmark test-info $1 frames) || die "error detecting length of $1"
-  local in2=$(audiowmark test-info $2 frames) || die "error detecting length of $2"
+  local in1="$($AUDIOWMARK test-info $1 frames)"
+  local in2="$($AUDIOWMARK test-info $2 frames)"
 
   [ "x$in1" != "x" ] || die "length of '$1' could not be detected"
   [ "x$in1" == "x$in2" ] || die "length of '$1' ($in1) and '$2' ($in2) differs"
+}
+
+check_snr()
+{
+  local snr="$($AUDIOWMARK test-snr $1 $2)"
+  echo >&2 "==== snr of $1 and $2 is $snr (expected $3) ===="
+  [ "x$snr" != "x" ] || die "snr of '$1' and '$2' could not be detected"
+  [ "x$3" != "x" ] || die "need snr bound"
+  awk "BEGIN {exit !($snr >= $3)}" || die "snr of '$1' and '$2' is worse than $3"
 }
