SRC: videowmark: use rf64 as format to support huge files
See also:
 - https://github.com/swesterfeld/audiowmark/issues/30

Signed-off-by: Stefan Westerfeld <stefan@space.twc.de>

diff --git a/src/videowmark b/src/videowmark
--- a/src/videowmark
+++ b/src/videowmark
@@ -85,11 +85,11 @@ function add_watermark
   local wm_wav=/dev/fd/4
 
   # get audio as wav
-  ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -f wav "$orig_wav" || die "extracting audio from video failed (ffmpeg)"
+  ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -f wav -rf64 always "$orig_wav" || die "extracting audio from video failed (ffmpeg)"
   # watermark
   [ -z "$QUIET" ] && echo >&2 "Audio Codec: $(audio_encode_options "$in_file")"
   audiowmark add "${AUDIOWMARK_ARGS[@]}" "$orig_wav" "$wm_wav" "$bits" \
-             --set-input-label "$in_file" --set-output-label "$out_file" || die "watermark generation failed (audiowmark)"
+             --set-input-label "$in_file" --set-output-label "$out_file" --output-format rf64 || die "watermark generation failed (audiowmark)"
   # rejoin
   ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -i "$wm_wav" -c:v copy $(audio_encode_options "$in_file") -map 0:v:0 -map 1:a:0 "$out_file" || \
     die "merging video and watermarked audio failed (ffmpeg)"
@@ -111,7 +111,7 @@ function get_watermark
   local wav=/dev/fd/3
 
   # get audio as wav
-  ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -f wav "$wav" || die "extracting audio from video failed (ffmpeg)"
+  ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -f wav -rf64 always "$wav" || die "extracting audio from video failed (ffmpeg)"
   # get watermark
   audiowmark get "${AUDIOWMARK_ARGS[@]}" "$wav" || die "retrieving watermark from audio failed (audiowmark)"
 }
